# Generated by Django 5.2.7 on 2025-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_budgets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_generate_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('project_manager', 'Project Manager'), ('field_officer', 'Field Officer'), ('finance_officer', 'Finance Officer'), ('monitoring_officer', 'Monitoring Officer'), ('viewer', 'Viewer')], default='field_officer', max_length=20),
        ),
    ]
