# Generated by Django 5.2.7 on 2025-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_approve_budgets_user_can_generate_reports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_approve_budgets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_generate_reports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_users',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('project_manager', 'Project Manager'), ('field_officer', 'Field Officer'), ('finance_officer', 'Finance Officer'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
