# Generated by Django 5.2.7 on 2025-10-04 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Unique project identifier or code.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('donor', models.CharField(default='Bill & Melinda Gates Foundation', max_length=150)),
                ('implementing_partner', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=20)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, help_text='Completion progress in percentage', max_digits=5)),
                ('project_manager', models.ForeignKey(blank=True, help_text='User responsible for managing this project', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
            },
        ),
    ]
