# Generated by Django 5.2.7 on 2025-10-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_actual_end_date_and_more'),
    ]

    operations = [
    ]
