# Generated by Django 5.2.7 on 2025-10-29 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Primary accountable person for project delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk_notes',
            field=models.TextField(blank=True, help_text='Detailed risk analysis, mitigation strategies, and contingency plans', null=True, verbose_name='Risk Assessment Notes'),
        ),
    ]
