# Generated by Django 5.2.7 on 2025-10-09 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('yield', 'Crop Yield'), ('income', 'Household Income'), ('training', 'Training Participation'), ('adoption', 'Technology Adoption'), ('nutrition', 'Nutrition & Health')], max_length=50)),
                ('description', models.TextField(help_text='Detailed explanation of the indicator being tracked.')),
                ('baseline_value', models.DecimalField(decimal_places=2, help_text='Initial measurement before intervention.', max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Latest measurement after intervention.', max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Planned or expected target value.', max_digits=10)),
                ('measurement_date', models.DateField()),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='farmers.farmer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='projects.project')),
            ],
            options={
                'verbose_name': 'Performance Indicator',
                'verbose_name_plural': 'Performance Indicators',
                'ordering': ['-measurement_date'],
            },
        ),
    ]
