# Generated by Django 5.2.7 on 2025-10-20 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringvisit',
            name='findings',
            field=models.TextField(default='Initial assessment in progress'),
        ),
        migrations.AlterField(
            model_name='monitoringvisit',
            name='purpose',
            field=models.CharField(default='Routine Monitoring', max_length=250),
        ),
        migrations.AlterField(
            model_name='monitoringvisit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monitoringvisit',
            name='visited_by',
            field=models.CharField(default='Field Officer', max_length=150),
        ),
    ]
