# Generated by Django 5.2.7 on 2025-10-20 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_monitoringvisit_findings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporting_period_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_period_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
