# Generated by Django 5.2.7 on 2025-10-06 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_household', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('family_size', models.PositiveIntegerField(default=1)),
                ('income_level', models.CharField(choices=[('low', 'Low Income'), ('medium', 'Medium Income'), ('high', 'High Income')], default='low', max_length=20)),
            ],
            options={
                'ordering': ['head_of_household'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='farmers', to='projects.project')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farmers.household')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='household',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='farmers.location'),
        ),
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('soil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_plots', to='farmers.farmer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
