# Generated by Django 5.2.7 on 2025-10-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RemoveField(
            model_name='farmplot',
            name='location',
        ),
        migrations.AlterField(
            model_name='household',
            name='income_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
