# Generated by Django 5.2.7 on 2025-10-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmer_options_alter_household_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmplot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_plots', to='farmers.location'),
        ),
    ]
